---
# vars file for mariadb

mysql_daemon: mariadb
mysql_dependencies:
  - python3-mysql

mysql_packages:
  - mariadb
  - mariadb-server
  - mariadb-connector-c
  - mariadb-backup

service_mariadb: mariadb

path_mariadb_conf: /etc/my.cnf

mysql_slow_query_log_file: /var/log/mysql-slow.log
mysql_log_error: /var/log/mariadb/mariadb.log
mysql_pid_file: /var/run/mariadb/mariadb.pid
mysql_config_file: /etc/my.cnf
mysql_config_include_dir: /etc/my.cnf.d

# The entries controlled by this value should not be used with MariaDB >= 10.2.2
# See https://github.com/frappe/bench/issues/681#issuecomment-398984706
mysql_supports_innodb_large_prefix: false
# __mysql_syslog_tag: mariadb
# __mysql_socket: /var/lib/mysql/mysql.sock
