---
dependency:
  name: galaxy
  # enabled: false
  options:
    # requirements-file: collections.yaml  # Collections
    # role-file: requirements.yaml
    ignore-errors: true
    # ignore-certs: True
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    driver: kvm
lint: |
  set -e
  yamllint -f colored .
  ansible-lint --force-color .
platforms:
  - name: f34-core
    box: fedora/34-cloud-base
    cpus: 2
    memory: 2048
    instance_raw_config_args:
      - 'vagrant.plugins = ["vagrant-libvirt"]'
    provider_raw_config_args:
      - "cpu_mode = 'host-passthrough'"
      - "disk_bus = 'virtio'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"
    provider_options:
      video_type: "'vga'"
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: "'vagrant'"
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
  config_options:
    defaults:
      stdout_callback: 'yaml'  # To get pretty output
      bin_ansible_callbacks: true
      interpreter_python: 'python3'
      verbosity: 1
    ssh_connection:
      pipelining: false
  options:
    vvv: true
    # vault-id: '@$HOME/.ansible/.vault.key'
  connection_options:
    ansible_ssh_user: vagrant
    # ansible_become: true
    ansible_connection: smart  # Override the connection: local
  env:
    PY_COLORS: true
    ANSIBLE_FORCE_COLOR: true
    # ANSIBLE_DEBUG: true
    # ANSIBLE_CONFIG: './ansible.cfg'
    # ANSIBLE_ROLES_PATH: "./roles"
    # ANSIBLE_COLLECTIONS_PATH: "./collections"
  log: true
  lint: |
    set -e
    yamllint .
    ansible-lint
    flake8
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
