---
# defaults file for jenkins

jenkins_service_enabled: true
jenkins_home: /home/jenkins
jenkins_service_name: jenkins
jenkins_user: jenkins
jenkins_group: jenkins
jenkins_hostname: localhost
jenkins_listen_address: 127.0.0.1
jenkins_http_port: 9093
jenkins_approle_role_id: ""
jenkins_approle_secret_id: ""

vault_uri: "https://vault.example.com"
...
