# Icons: ïŒŠ  ï®  ï‘– ï™• ï ï ï ½ ï ¿ ï†’ ï‘§ ï”™ ï™• ïœ  ï ï ï• ïŠ ï ½ î—¿  ğŸ”’ï˜½ ï” ï™ ï‘ 

format = """
[ ïŒŠ  $shell](fg:#fbf1c7 bg:#4e9dd3)\
[î‚°](fg:#4E9DD3 bg:#1d2021)\
$username\
$hostname\
[î‚°](fg:#1d2021 bg:#458588)\
$directory\
[î‚°](fg:#458588 bg:#d79921)\
$git_branch\
$git_status\
[î‚°](fg:#d79921)\
$fill\
$line_break\
$character\
$sudo\
"""

right_format = """
[î‚²](fg:#a89984)\
$time\
"""

# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[fill]
symbol = " "
# style = "bold green"

[username]
show_always = true
# style_user = "fg:#d79921 bg:#282828"
style_user = "fg:#d79921 bg:#1d2021"
style_root = "fg:#fb4934"
format = '[ $user]($style)'

[hostname]
ssh_only = false
# trim_at = ".oswee.com"
disabled = false
style = "fg:#d79921 bg:#1d2021"
format = "[$ssh_symbol](bold blue)[@]($style)[$hostname ]($style)"

[directory]
# style = "fg:#fbf1c7 bg:#458588"
style = "fg:#282828 bg:#458588"
read_only = "ï® "
read_only_style = "fg:#fbf1c7 bg:#458588"
truncation_length = 5
truncation_symbol = "â€¦/"
home_symbol = " ~"
repo_root_style = "fg:#fbf1c7 bg:#458588"
repo_root_format = '[ î—» $before_root_path]($repo_root_style)[$repo_root]($repo_root_style)[$path ]($repo_root_style)[$read_only]($read_only_style)'
format = '[ î—¾ $path ]($style)[$read_only]($read_only_style)'

[git_branch]
style = "fg:#282828 bg:#d79921"
symbol = "ï‡“ "
truncation_length = 6
truncation_symbol = ""
# ignore_branches = ["master", "main"]
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#282828 bg:#d79921"
format = '[ $all_status $ahead_behind ]($style)'

[line_break]

[character]
success_symbol = "[ï”](fg:#fbf1c7)"
error_symbol = "[ï”](fg:#fb4934)"

[time]
disabled = false
time_format = "%T"
style = "fg:#282828 bg:#a89984"
format = '[ $time ]($style)'

[sudo]
style = "fg:#fb4934"
symbol = "ï‘„ "
format = "[$symbol]($style)"
disabled = false

[shell]
# zsh_indicator = "î® "
# bash_indicator = "ï…•"
# nu_indicator = "ï„  "
zsh_indicator = "Zsh "
bash_indicator = "Bash "
nu_indicator = "Nu "
style = "fg:#fbf1c7 bg:#4e9dd3"
format = "[$indicator]($style)"
disabled = false

