---
# ansible_host_key_checking: no

become_user: 'ansible'

hostname: 'dhcp'
host_octet: '252'
uuid: '0ae7c565-029a-43e4-a13a-84de3d67bb46'
vcpu: '1'
memory: 1024
disk_size: 5
mac: '00:1a:4a:16:01:26'
dhcp_network_interface: 'eth0'
