---
# tasks file for nodejs

- name: Install NodeJS
  import_tasks: install.yml
  tags:
    - nodejs:setup
    - nodejs:setup:install

# - name: Update configuration
#   import_tasks: configure.yml
#   tags:
#     - nodejs:setup
#     - nodejs:setup:config

# - name: Remove NodeJS
#   import_tasks: remove.yml
#   tags:
#     - nodejs:remove
