---
# tasks file for haproxy

# - include_role:
#     name: dzintars.haproxy

- name: Ensure certs directory exists
  become: true
  file:
    path: "/etc/letsencrypt/live/{{ root_domain }}"
    state: directory
    mode: '0755'

- name: Copy private SSL certificates from Ansible Vault
  become: true
  ansible.builtin.copy:
    content: "{{ tls_certs[0].content }}"
    dest: "/etc/letsencrypt/live/{{ root_domain }}/haproxy.pem"
    owner: '{{ haproxy_user }}'
    group: '{{ haproxy_group }}'
    mode: "u=rw,g=r,o="

- name: Copy haproxy.cfg and reload HAProxy
  become: true
  ansible.builtin.template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: '0644'
    validate: haproxy -f %s -c -q
  notify:
    - Restart HAProxy
