# Icon samples: ïŒŠ ï® ï‘– ï™• ï ï ï ½ ï ¿ ï†’ ï‘§ ï”™ ï™• ïœ  ï ï ï• ïŠ ï ½ î—¿ ğŸ”’ï˜½ ï” ï™ ï‘  î‚¶

format = """
[ ïŒŠ  ](fg:fg0 bg:bg4)\
$shell\
[î‚°](fg:bg4 bg:orange)\
[î‚°](fg:orange bg:blue)\
$username\
[@](fg:fg0 bg:blue)\
$hostname\
[î‚°](fg:blue bg:orange)\
[î‚°](fg:orange bg:fg4)\
$directory\
[î‚°](fg:fg4 bg:orange)\
[î‚°](fg:orange bg:yellow)\
$git_branch\
$git_status\
[î‚°](fg:yellow)\
$fill\
$line_break\
$character\
$sudo\
"""

right_format = """
[î‚²](fg:fg1)\
$time\
"""

# Inserts a blank line between shell prompts
add_newline = false
palette = "light"

# Theme names are inversed from the original Gruvbox scheme
[palettes.light]
orange_neutral	= "#d65d0e"
red_neutral			= "#cc241d"
green_neutral		= "#98971a"
yellow_neutral	= "#d79921"
blue_neutral		= "#458588"
purple_neutral	= "#b16286"
aqua_neutral		= "#689d6a"
gray_neutral		= "#928374"
orange					= "#fe8019"
red							= "#fb4934"
green						= "#b8bb26"
yellow					= "#fabd2f"
blue						= "#83a598"
purple					= "#d3869b"
aqua						= "#8ec07c"
gray						= "#a89984"
fg0							= "#fbf1c7"
fg1							= "#ebdbb2"
fg2							= "#d5c4a1"
fg3							= "#bdae93"
fg4							= "#a89984"
bg0							= "#282828"
bg0_hard				= "#1d2021"
bg0_soft				= "#32302f"
bg1							= "#3c3836"
bg2							= "#504945"
bg3							= "#665c54"
bg4							= "#7c6f64"

# Theme names are inversed from the original Gruvbox scheme
[palettes.dark]
orange_neutral	= "#d65d0e"
red_neutral			= "#cc241d"
green_neutral		= "#98971a"
yellow_neutral	= "#d79921"
blue_neutral		= "#458588"
purple_neutral	= "#b16286"
aqua_neutral		= "#689d6a"
gray_neutral		= "#928374"
orange					= "#af3a03"
red							= "#9d0006"
green						= "#79740e"
yellow					= "#b57614"
blue						= "#076678"
purple					= "#8f3f71"
aqua						= "#427b58"
gray						= "#7c6f64"
fg0							= "#282828"
fg1							= "#3c3836"
fg2							= "#504945"
fg3							= "#665c54"
fg4							= "#7c6f64"
bg0							= "#fbf1c7"
bg0_hard				= "#f9f5d7"
bg0_soft				= "#f2e5bc"
bg1							= "#ebdbb2"
bg2							= "#d5c4a1"
bg3							= "#bdae93"
bg4							= "#a89984"


[fill]
symbol = " "

[username]
show_always = true
style_user = "bold fg:fg0 bg:blue"
style_root = "bold fg:red bg:blue"
format = '[ $user]($style)'

[hostname]
ssh_only = false
trim_at = ".oswee.com"
style = "fg:fg0 bg:blue"
format = "[$hostname ]($style)"
disabled = false

[directory]
style = "fg:fg0 bg:fg4"
read_only = "ï® "
read_only_style = "fg:orange bg:fg4"
truncation_length = 5
truncation_symbol = "â€¦/"
home_symbol = " ~"
repo_root_style = "fg:fg0 bg:fg4"
repo_root_format = '[ î—» $before_root_path]($repo_root_style)[$repo_root]($repo_root_style)[$path ]($repo_root_style)[$read_only]($read_only_style)'
format = '[ î—¾ $path ]($style)[$read_only]($read_only_style)'

[git_branch]
style = "fg:fg4 bg:yellow"
symbol = "ï‡“ "
truncation_length = 6
truncation_symbol = ""
# ignore_branches = ["master", "main"]
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:fg4 bg:yellow"
format = '[ $all_status $ahead_behind ]($style)'

[line_break]

[character]
success_symbol = "[ï‘ ](fg:aqua)"
error_symbol = "[ï‘ ](fg:red)"

[time]
disabled = false
time_format = "%T"
style = "fg:bg0 bg:fg1"
format = '[ $time ]($style)'

[sudo]
style = "fg:red"
symbol = "ï‘„ "
format = "[$symbol]($style)"
disabled = false

[shell]
# zsh_indicator = "î® "
# bash_indicator = "ï…•"
# nu_indicator = "ï„  "
zsh_indicator = "Zsh "
bash_indicator = "Bash "
nu_indicator = "Nu "
style = "fg:fg0 bg:bg4"
format = "[$indicator]($style)"
disabled = false

