---
# tasks file for nvim

- name: Create NeoVim config root directory.
  ansible.builtin.file:
    path: '{{ nvim_config_dir }}'
    state: directory
    # owner: '{{ ansible_user_id }}'

- name: Create NeoVim config directories.
  ansible.builtin.file:
    path: '{{ nvim_config_dir }}/{{ item }}'
    state: directory
    mode: '0755'
    # owner: '{{ ansible_user_id }}'
  loop:
    - 'sessions'
    - 'undodir'

- name: Copy Neovim settings
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ nvim_config_dir }}/{{ item.dest }}/'
    mode: '0644'
  loop:
    - { src: 'lua/modules/core/settings.lua', dest: '/lua/modules/core' }

- name: Include settings
  ansible.builtin.lineinfile:
    path: '{{ nvim_config_dir }}/init.lua'
    line: "require('modules.core.settings')"
    regexp: "^require('modules.core.settings')$"
    state: present
    # insertafter: '^-- Settings'
    create: true
...
