---
# tasks file for nvim

- name: Clone NeoVim repository
  ansible.builtin.git:
    repo: '{{ nvim_repo_url }}'
    dest: '{{ nvim_source_dir }}'
    version: master
    depth: 1
  when: nvim_nightly | bool
  register: nvim_repo

- name: Cleanup build artifacts
  community.general.make:
    chdir: '{{ nvim_source_dir }}'
    target: clean
  when: nvim_repo.changed

- name: Build NeoVim from the source
  community.general.make:
    chdir: '{{ nvim_source_dir }}'
    target: nvim
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: nvim_repo.changed
  register: nvim_build

- name: Install build version of the NeoVim
  become: true
  community.general.make:
    chdir: '{{ nvim_source_dir }}'
    target: install
  when: nvim_build.changed
