---
# tasks file for mariadb

- name: mariadb | install rpm dependencies
  become: true
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - '{{ mysql_dependencies }}'

- name: mariadb | install rpm mariadb
  become: true
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: latest
    update_cache: true
  loop:
    - '{{ mysql_packages }}'
  register: mysql_install_packages
