---
# install tasks file for protoc

- name: Ensure protoc directory exists
  ansible.builtin.file:
    path: '{{ protoc_dir }}'
    state: directory
    # mode: '0755'
    mode: "u=rwx,go=rx"

- name: Install unzip package
  become: true
  ansible.builtin.dnf:
    name: unzip.x86_64
    state: present

- name: Download Protoc compiler
  ansible.builtin.unarchive:
    src: https://github.com/protocolbuffers/protobuf/releases/download/v{{ protoc_version }}/protoc-{{ protoc_version }}-linux-x86_64.zip
    dest: '{{ protoc_dir }}'
    remote_src: true
    group: '{{ protoc_group }}'

- name: Add Protoc to system-wide $PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/protoc.sh
    content: "export PATH={{ protoc_dir }}/bin:{{ protoc_dir }}/include:$PATH\n"
...
