---
- name: remove libvirt and it's dependencies
  become: true
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: absent
  loop:
    - libvirt
    - virt-install
    - virt-manager
    - bridge-utils
    - qemu-kvm
    - virt-top
    - libguestfs-tools
    - libvirt-devel
    - libvirt-daemon-kvm
