---
# tasks file for vault

# TODO: 1: Disable mlock

- name: Install rpm keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - https://rpm.releases.hashicorp.com/gpg

- name: Install HashiCorp repository
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.redhat }}"

- name: Copy Vault systemd sevice unit
  ansible.builtin.copy:
    src: vault.service
    dest: /etc/systemd/system/vault.service
    mode: '0644'

- name: Create Vault system group
  ansible.builtin.group:
    name: vault
    state: present
    system: true

- name: Create Vault user
  ansible.builtin.user:
    name: vault
    home: /etc/vault.d
    system: true
    shell: /bin/false
    group: vault

- name: Force systemd to re-execute itself (2.8 and above)
  ansible.builtin.systemd:
    daemon_reexec: true

- name: Allow the service to be accessed at the firewall level
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  notify: Restart Firewalld
  loop:
    - 8200/tcp
    - 8201/tcp

# - name: Allow the service to be accessed at the firewall level
#   ansible.posix.firewalld:
#     port: 8201/tcp
#     permanent: true
#     state: enabled
#   notify: Restart Firewalld

# https://www.vaultproject.io/docs/configuration#parameters
# Actually we don't need to do this because it's done in Systemd unit file.
# - name: Set mlock capabilities
#   become: true
#   community.general.capabilities:
#     path: /usr/bin/vault
#     capability: cap_ipc_lock=+ep
#     state: present

# - name: install packages
#   become: true
#   ansible.builtin.package:
#     name: "{{ item }}"
#     update_cache: true
#   with_items: "{{ vault_install_prerequisites }}"

# - name: download Hashicorp Vault
#   ansible.builtin.unarchive:
#     src: https://releases.hashicorp.com/vault/1.6.1/vault_1.6.1_linux_amd64.zip
#     dest: /tmp
#     remote_src: true

# - name: copy Vault binary
#   become: true
#   ansible.builtin.copy:
#     src: /tmp/vault
#     dest: /usr/local/bin
#     mode: a+x
#     remote_src: true
...
